#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct curpid_pin_ctx_t{ // found in shared/comps/curpid.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t en;
   hal_pin_inst_t cmd_mode;
   hal_pin_inst_t id_cmd;
   hal_pin_inst_t iq_cmd;
   hal_pin_inst_t id_fb;
   hal_pin_inst_t iq_fb;
   hal_pin_inst_t ac_current;
   hal_pin_inst_t ud;
   hal_pin_inst_t uq;
   hal_pin_inst_t max_cur;
   hal_pin_inst_t pwm_volt;
   hal_pin_inst_t r;
   hal_pin_inst_t ld;
   hal_pin_inst_t lq;
   hal_pin_inst_t psi;
   hal_pin_inst_t ff;
   hal_pin_inst_t kp;
   hal_pin_inst_t ki;
   hal_pin_inst_t ksp;
   hal_pin_inst_t kind;
   hal_pin_inst_t kci;
   hal_pin_inst_t scale;
   hal_pin_inst_t vel;
   hal_pin_inst_t id_error;
   hal_pin_inst_t iq_error;
};
