#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct dq_pin_ctx_t{ // found in shared/comps/dq.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t mode;
   hal_pin_inst_t u;
   hal_pin_inst_t v;
   hal_pin_inst_t w;
   hal_pin_inst_t pos;
   hal_pin_inst_t polecount;
   hal_pin_inst_t a;
   hal_pin_inst_t b;
   hal_pin_inst_t y;
   hal_pin_inst_t d;
   hal_pin_inst_t q;
};
