#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct sensorless_pin_ctx_t{ // found in shared/comps/sensorless.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t r;
   hal_pin_inst_t l;
   hal_pin_inst_t ki;
   hal_pin_inst_t kb;
   hal_pin_inst_t kl;
   hal_pin_inst_t min_vel;
   hal_pin_inst_t vel_boost;
   hal_pin_inst_t max_vel;
   hal_pin_inst_t id;
   hal_pin_inst_t iq;
   hal_pin_inst_t ud;
   hal_pin_inst_t uq;
   hal_pin_inst_t ud1;
   hal_pin_inst_t uq1;
   hal_pin_inst_t ud2;
   hal_pin_inst_t uq2;
   hal_pin_inst_t vel;
   hal_pin_inst_t pos;
   hal_pin_inst_t ed;
   hal_pin_inst_t eq;
   hal_pin_inst_t old_id;
   hal_pin_inst_t old_iq;
   hal_pin_inst_t delta_id;
   hal_pin_inst_t delta_iq;
};
