#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct sim_pin_ctx_t{ // found in shared/comps/sim.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t amp;
   hal_pin_inst_t freq;
   hal_pin_inst_t sin;
   hal_pin_inst_t msin;
   hal_pin_inst_t sin2;
   hal_pin_inst_t msin2;
   hal_pin_inst_t sin3;
   hal_pin_inst_t msin3;
   hal_pin_inst_t square;
   hal_pin_inst_t vel;
   hal_pin_inst_t res;
   hal_pin_inst_t offset;
};
