#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct hv_pin_ctx_t{ // found in stm32f303/src/comps/hv.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t drop;
   hal_pin_inst_t iu;
   hal_pin_inst_t iv;
   hal_pin_inst_t iw;
   hal_pin_inst_t u;
   hal_pin_inst_t v;
   hal_pin_inst_t w;
   hal_pin_inst_t udc;
   hal_pin_inst_t enu;
   hal_pin_inst_t env;
   hal_pin_inst_t enw;
   hal_pin_inst_t min_on;
   hal_pin_inst_t min_off;
   hal_pin_inst_t arr;
};
