#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct io_pin_ctx_t{ // found in stm32f303/src/comps/io.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t led;
   hal_pin_inst_t iu;
   hal_pin_inst_t iv;
   hal_pin_inst_t iw;
   hal_pin_inst_t iabs;
   hal_pin_inst_t u;
   hal_pin_inst_t v;
   hal_pin_inst_t w;
   hal_pin_inst_t udc;
   hal_pin_inst_t hv_temp;
   hal_pin_inst_t mot_temp;
   hal_pin_inst_t uo;
   hal_pin_inst_t vo;
   hal_pin_inst_t wo;
   hal_pin_inst_t dac;
   hal_pin_inst_t cu;
   hal_pin_inst_t cv;
   hal_pin_inst_t cw;
   hal_pin_inst_t hv_en;
   hal_pin_inst_t fault;
   hal_pin_inst_t ignore_fault_pin;
   hal_pin_inst_t brk_present;
   hal_pin_inst_t brk;
};
