:lang: en

= Parameter tuning

== Requirements
- link:supply.adoc[supply]
- link:servoterm.adoc[servoterm]
- link:feedback.adoc[feedback]
- link:motor.adoc[motor]

== electrical parameters
=== dc motor
==== manual tuning
[source]
conf0.r // motor phase resistance
conf0.l // motor phase inductance
conf0.psi // torque constant [Nm/A] or [V/rad/s]
conf0.mot_fb_rev

==== auto tuning
this takes about 20 seconds +
disconnect the motor from the load +
the motor will move +
follow the green instructions in Servoterm

- set your config to
[source]
link pid
link dc
link <your_feedback_type>
link misc
link iddc

- reset stmbl by typing
[source]
reset

- start the tuning by typing
[source]
fault0.en = 1

- lock the rotor and type
[source]
iddc0.state = 1.2

- unlock the rotor and type
[source]
iddc0.state = 2.2

- append the result (conf0.r, conf0.l, conf0.psi, opt. conf0.out_rev) to your config
- go to <<mechanical parameters>>

=== pmsm motor
==== manual tuning
[source]
conf0.r // motor phase resistance
conf0.l // motor phase inductance
conf0.polecount // number of pole pairs
conf0.mot_fb_offset
conf0.out_rev
conf0.psi // torque constant [Nm/A] or [V/rad/s]

==== auto tuning
this takes about 20 seconds +
disconnect the motor from the load +
the motor will move +
follow the green instructions in Servoterm

- set your config to
[source]
link pid
link dc
link <your_feedback_type>
link misc
link idpmsm

- reset stmbl by typing
[source]
reset

- start the tuning by typing
[source]
fault0.en = 1

- append the result (conf0.r, conf0.l, conf0.psi, conf0.polecount, conf0.mot_fb_offset, opt. conf0.out_rev) to your config
- go to <<mechanical parameters>>

== mechanical parameters
connect the motor to the load

=== manual tuning
[source]
conf0.j
conf0.j_load

=== auto tuning
this takes about 3 minutes +
connect the motor to the load +
the motor will move +
follow the green instructions in Servoterm

- set your config to
[source]
link pid
link <your_motor_type>
link <your_feedback_type>
link misc
link idm
<your_electrical_parameters>

- reset stmbl by typing
[source]
reset

- start the tuning by typing
[source]
fault0.en = 1

- append the result (conf0.j, conf0.d, conf0.f) to your config
- go to <<control loop tuning>>

== control loop tuning
=== manual tuning
[source]
conf0.pos_bw
conf0.vel_bw
conf0.vel_d

=== auto tuning
this takes about 2 minutes +
connect the motor to the load +
the motor will move +
follow the green instructions in Servoterm

- set your config to
[source]
link pid
link <your_motor_type>
link <your_feedback_type>
link misc
link ids
<your_electrical_parameters>
<your_mechanical_parameters>

- reset stmbl by typing
[source]
reset

- start the tuning by typing
[source]
fault0.en = 1

- append the result (conf0.pos_bw, conf0.vel_bw, conf0.vel_d) to your config
- go to link:cmd.adoc[cmd]

