:lang: en

= Parameter tuning

== Requirements
- link:supply.adoc[supply]
- link:servoterm.adoc[servoterm]
- link:feedback.adoc[feedback]
- link:motor.adoc[motor]

== electrical parameters
=== dc motor
==== manual tuning
[source]
conf0.r // motor phase resistance
conf0.l // motor phase inductance
conf0.psi // torque constant [Nm/A] or [V/rad/s]
conf0.mot_fb_rev

==== auto tuning
this takes about 20 seconds +
disconnect the motor from the load +
the motor will turn with a max velocity of iddc0.test_vel (rad/s) and apply a max current of iddc0.test_cur (A) +
follow the green instructions in Servoterm

- set your config to
[source]
link pid
link dc
link <your_feedback_type>
link misc
link id_dc

- reset stmbl by typing
[source]
reset

- start the tuning by typing
[source]
fault0.en = 1

- lock the rotor and type
[source]
iddc0.state = 1.2

- unlock the rotor and type
[source]
iddc0.state = 2.2

- append the result (conf0.r, conf0.l, conf0.psi, opt. conf0.out_rev) to your config
- go to <<mechanical parameters>>

=== pmsm motor
==== manual tuning
[source]
conf0.r // motor phase resistance
conf0.l // motor phase inductance
conf0.polecount // number of pole pairs
conf0.mot_fb_offset
conf0.out_rev
conf0.psi // torque constant [Nm/A] or [V/rad/s]

==== auto tuning
this takes about 20 seconds +
disconnect the motor from the load +
the motor will turn with a max velocity of idpmsm0.test_vel (rad/s) and apply a max current of idpmsm0.test_cur (A) +
follow the green instructions in Servoterm

- set your config to
[source]
link pid
link pmsm
link <your_feedback_type>
link misc
link id_pmsm

- reset stmbl by typing
[source]
reset

- start the tuning by typing
[source]
fault0.en = 1

- append the result (conf0.r, conf0.l, conf0.psi, conf0.polecount, conf0.mot_fb_offset, opt. conf0.out_rev) to your config
- go to <<motor mechanical parameters>>

== motor mechanical parameters

=== manual tuning
[source]
conf0.j

=== auto tuning
this takes about 2 minutes +
disconnect the motor from the load +
the motor will move between idm0.min_pos (rad) and idm0.max_pos (rad) with a max velocity of idm0.max_vel (rad/s) and a max acceleration of idm0.max_acc (rad/s^2) +
follow the green instructions in Servoterm

- set your config to
[source]
link pid
link <your_motor_type>
link <your_feedback_type>
link misc
link id_mot
<your_electrical_parameters>

- reset stmbl by typing
[source]
reset

- start the tuning by typing
[source]
fault0.en = 1

- append the result (conf0.j, conf0.d, conf0.f, conf0.o) to your config
- go to <<system mechanical parameters>>

== system mechanical parameters
you can skip this step if you want to tune the motor without load +

=== manual tuning
[source]
conf0.j_sys
conf0.j_lpf

=== auto tuning
this takes about 2 minutes +
connect the motor to the load +
the motor will move between idm0.min_pos (rad) and idm0.max_pos (rad) with a max velocity of idm0.max_vel (rad/s) and a max acceleration of idm0.max_acc (rad/s^2) +
follow the green instructions in Servoterm

- set your config to
[source]
link pid
link <your_motor_type>
link <your_feedback_type>
link misc
link id_sys
<your_electrical_parameters>
<your_mechanical_parameters>

- reset stmbl by typing
[source]
reset

- start the tuning by typing
[source]
fault0.en = 1

- append the result (conf0.j_sys, conf0.d, conf0.f, conf0.o) to your config
- go to <<control loop tuning>>

== control loop tuning
=== manual tuning
[source]
conf0.pos_bw
conf0.vel_bw
conf0.vel_d

=== auto tuning
this takes about 2 minutes +
connect the motor to the load +
the motor will move between ids0.min_pos (rad) and ids0.max_pos (rad) with a max velocity of ids0.max_vel (rad/s) and a max acceleration of ids0.max_acc (rad/s^2) +
follow the green instructions in Servoterm

- set your config to
[source]
link pid
link <your_motor_type>
link <your_feedback_type>
link misc
link id_pid
<your_electrical_parameters>
<your_mechanical_parameters>

- reset stmbl by typing
[source]
reset

- start the tuning by typing
[source]
fault0.en = 1

- append the result (conf0.pos_bw, conf0.vel_bw, conf0.vel_d) to your config
- go to link:cmd.adoc[cmd]

