:lang: en

= Parameter tuning

== Requirements
- link:supply[supply]
- link:servoterm[servoterm]
- link:feedback[feedback]
- link:motor[motor]

== electrical parameters
disconnect the motor from the load

=== dc motor
==== manual tuning
[source]
conf0.r // motor phase resistance
conf0.l // motor phase inductance
conf0.psi // torque constant [Nm/A] or [V/rad/s]

==== auto tuning
this takes about 20 seconds
the motor will move
follow the instructions in Servoterm

config:
[source]
link pid
link dc
link <your_feedback_type>
link misc
link iddc

start:
[source]
fault0.en = 1

example output:
[source]
OK fault0.en = 1.000000
INFO: Enabled
Measure r, l
block the rotor
id0.state = 1.2 to start
OK id0.state = 1.200000
conf0.r = 1.898350
conf0.l = 0.013483
Measure torque constant
unblock the rotor
the motor will move
id0.state = 2.2 to start
OK id0.state = 2.200000
conf0.psi = 0.063680

=== pmsm motor
==== manual tuning
[source]
conf0.r // motor phase resistance
conf0.l // motor phase inductance
conf0.polecount // number of pole pairs
conf0.mot_fb_offset
conf0.mot_fb_rev
conf0.psi // torque constant [Nm/A] or [V/rad/s]

==== auto tuning
this takes about 20 seconds
the motor will move

config:
[source]
link pid
link pmsm
link <your_feedback_type>
link misc
link idpmsm

start:
[source]
fault0.en = 1

example output:
[source]
OK fault0.en = 1.000000
INFO: Enabled
conf0.r = 1.898350
conf0.l = 0.013483
conf0.polecount = 4.000000
conf0.mot_fb_offset = -0.258811
conf0.psi = 0.063680

== mechanical parameters
connect the motor to the load

=== manual tuning
[source]
conf0.j
conf0.j_load

=== auto tuning
this takes about 3 minutes
the motor will move

config:
[source]
link pid
link <your_motor_type>
link <your_feedback_type>
link misc
link idm
<your_electrical_parameters>

start:
[source]
fault0.en = 1

example output:
[source]
OK fault0.en = 1.000000
INFO: Enabled
conf0.j = 0.000085
conf0.d = 0.000022
conf0.f = 0.057124

== control loop tuning
=== manual tuning
[source]
conf0.pos_bw
conf0.vel_bw
conf0.vel_d

=== auto tuning
this takes about 2 minutes
the motor will move

config:
[source]
link pid
link <your_motor_type>
link <your_feedback_type>
link misc
link ids
<your_electrical_parameters>
<your_mechanical_parameters>

start:
[source]
fault0.en = 1

example output:
[source]
OK fault0.en = 1.000000
INFO: Enabled
conf0.pos_bw = 24.165899
conf0.vel_bw = 450.000000
conf0.vel_d = 6.058537