//generated by tools/create_cmd.py DO NOT EDIT
extern void bootloader(char *); // found in src/main.c line: 101
extern void nv_reset(char *); // found in src/main.c line: 106
extern void about(char *); // found in src/main.c line: 162
extern void sleep(char *); // found in src/main.c line: 173
extern void confcrc(char *); // found in src/config.c line: 40
extern void flashloadconf(char *); // found in src/config.c line: 45
extern void flashsaveconf(char *); // found in src/config.c line: 68
extern void loadconf(char *); // found in src/config.c line: 73
extern void showconf(char *); // found in src/config.c line: 78
extern void appendconf(char *); // found in src/config.c line: 85
extern void deleteconf(char *); // found in src/config.c line: 90
extern void hardboot(char *); // found in src/config.c line: 104
extern void hv_send(char *); // found in src/comps/hv.c line: 112
extern void send_boot(char *); // found in src/comps/hv.c line: 528
extern void jog_left(char *); // found in shared/comps/jog.c line: 28
extern void jog_right(char *); // found in shared/comps/jog.c line: 29
extern void jog_stop(char *); // found in shared/comps/jog.c line: 30
extern void hal_term_print_info(char *); // found in shared/hal.c line: 266
extern void load(char *); // found in shared/hal.c line: 517
extern void show(char *); // found in shared/hal.c line: 532
extern void list(char *); // found in shared/hal.c line: 562
extern void show_hal(char *); // found in shared/hal.c line: 572
extern void hal_start(char *); // found in shared/hal.c line: 675
extern void hal_stop(char *); // found in shared/hal.c line: 702
extern void fault(char *); // found in shared/hal.c line: 951
extern void debug_level(char *); // found in shared/hal.c line: 966
extern void hal_linked_pins(char *); // found in shared/hal.c line: 991
extern void hal_relink_pins(char *); // found in shared/hal.c line: 1001
extern void listcmd(char *); // found in shared/commands.c line: 36
extern void uptime(char *); // found in shared/commands.c line: 47
extern void link(char *); // found in shared/config.c line: 18
extern void show_config_template(char *); // found in shared/config.c line: 35


cmd_t cmd[] = {
   {"bootloader", "enter bootloader", bootloader}, // found in src/main.c line: 101
   {"reset", "reset STMBL", nv_reset}, // found in src/main.c line: 106
   {"about", "show system infos", about}, // found in src/main.c line: 162
   {"sleep", "sleep [s]", sleep}, // found in src/main.c line: 173
   {"confcrc", "foo", confcrc}, // found in src/config.c line: 40
   {"flashloadconf", "load config from flash", flashloadconf}, // found in src/config.c line: 45
   {"flashsaveconf", "save config to flash", flashsaveconf}, // found in src/config.c line: 68
   {"loadconf", "parse config", loadconf}, // found in src/config.c line: 73
   {"showconf", "show config", showconf}, // found in src/config.c line: 78
   {"appendconf", "append string to config", appendconf}, // found in src/config.c line: 85
   {"deleteconf", "delete config", deleteconf}, // found in src/config.c line: 90
   {"hardboot", "destroy firmware to force bootloader", hardboot}, // found in src/config.c line: 104
   {"hv", "send command to hv board", hv_send}, // found in src/comps/hv.c line: 112
   {"hv_update", "try hv update", send_boot}, // found in src/comps/hv.c line: 528
   {"jogl", "Jog left", jog_left}, // found in shared/comps/jog.c line: 28
   {"jogr", "Jog right", jog_right}, // found in shared/comps/jog.c line: 29
   {"jogx", "Stop jog", jog_stop}, // found in shared/comps/jog.c line: 30
   {"hal", "print HAL stats", hal_term_print_info}, // found in shared/hal.c line: 266
   {"load", "load comp from flash", load}, // found in shared/hal.c line: 517
   {"show", "show comps in flash", show}, // found in shared/hal.c line: 532
   {"list", "show comp instances", list}, // found in shared/hal.c line: 562
   {"show_hal", "show hal structure", show_hal}, // found in shared/hal.c line: 572
   {"start", "start rt system", hal_start}, // found in shared/hal.c line: 675
   {"stop", "stop rt system", hal_stop}, // found in shared/hal.c line: 702
   {"fault", "trigger fault", fault}, // found in shared/hal.c line: 951
   {"debug_level", "set hal debug level, 0 = print all, 1 = print errors, 2 = no output", debug_level}, // found in shared/hal.c line: 966
   {"linked", "show linked pins", hal_linked_pins}, // found in shared/hal.c line: 991
   {"relink", "relink all hal pins (a = b, b = c => a = c, b = c)", hal_relink_pins}, // found in shared/hal.c line: 1001
   {"help", "print this", listcmd}, // found in shared/commands.c line: 36
   {"uptime", "display uptime", uptime}, // found in shared/commands.c line: 47
   {"link", "load config template", link}, // found in shared/config.c line: 18
   {"show_config", "show config templates", show_config_template}, // found in shared/config.c line: 35
};
