#pragma once
//generated by tools/create_hal_tbl.py DO NOT EDIT

struct pin_ctx_t{
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
};

struct hv_pin_ctx_t{ // found in stmsp/stm32f303/src/comps/hv.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t a;
   hal_pin_inst_t b;
   hal_pin_inst_t a_fb;
   hal_pin_inst_t b_fb;
   hal_pin_inst_t udc;
   hal_pin_inst_t hv_temp;
   hal_pin_inst_t en;
   hal_pin_inst_t ena;
   hal_pin_inst_t enb;
   hal_pin_inst_t fault;
   hal_pin_inst_t min_on;
   hal_pin_inst_t min_off;
};

struct io_pin_ctx_t{ // found in stmsp/stm32f303/src/comps/io.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t led;
   hal_pin_inst_t oc1;
   hal_pin_inst_t oc2;
   hal_pin_inst_t ena;
   hal_pin_inst_t enb;
   hal_pin_inst_t hv_temp;
   hal_pin_inst_t dc_link;
   hal_pin_inst_t bemf0;
   hal_pin_inst_t bemf1;
   hal_pin_inst_t in0;
   hal_pin_inst_t in1;
   hal_pin_inst_t iap;
   hal_pin_inst_t ian;
   hal_pin_inst_t ibp;
   hal_pin_inst_t ibn;
   hal_pin_inst_t ip;
   hal_pin_inst_t in;
   hal_pin_inst_t ia;
   hal_pin_inst_t ib;
};

struct tle_pin_ctx_t{ // found in stmsp/stm32f303/src/comps/tle.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t pos;
   hal_pin_inst_t error;
};

struct sim_pin_ctx_t{ // found in shared/comps/sim.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t amp;
   hal_pin_inst_t freq;
   hal_pin_inst_t sin;
   hal_pin_inst_t msin;
   hal_pin_inst_t sin2;
   hal_pin_inst_t msin2;
   hal_pin_inst_t sin3;
   hal_pin_inst_t msin3;
   hal_pin_inst_t square;
   hal_pin_inst_t vel;
   hal_pin_inst_t res;
   hal_pin_inst_t offset;
};

struct term_pin_ctx_t{ // found in shared/comps/term.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t wave[8];
   hal_pin_inst_t offset[8];
   hal_pin_inst_t gain[8];
   hal_pin_inst_t send_step;
   hal_pin_inst_t con;
};

struct curpid_pin_ctx_t{ // found in shared/comps/curpid.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t en;
   hal_pin_inst_t cmd_mode;
   hal_pin_inst_t id_cmd;
   hal_pin_inst_t iq_cmd;
   hal_pin_inst_t id_fb;
   hal_pin_inst_t iq_fb;
   hal_pin_inst_t ac_current;
   hal_pin_inst_t ud;
   hal_pin_inst_t uq;
   hal_pin_inst_t max_cur;
   hal_pin_inst_t pwm_volt;
   hal_pin_inst_t rd;
   hal_pin_inst_t rq;
   hal_pin_inst_t ld;
   hal_pin_inst_t lq;
   hal_pin_inst_t psi;
   hal_pin_inst_t ff;
   hal_pin_inst_t kp;
   hal_pin_inst_t ki;
   hal_pin_inst_t kind;
   hal_pin_inst_t vel;
   hal_pin_inst_t id_error;
   hal_pin_inst_t iq_error;
};

struct svm_pin_ctx_t{ // found in shared/comps/svm.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t u;
   hal_pin_inst_t v;
   hal_pin_inst_t w;
   hal_pin_inst_t udc;
   hal_pin_inst_t su;
   hal_pin_inst_t sv;
   hal_pin_inst_t sw;
   hal_pin_inst_t cmode;
   hal_pin_inst_t mode;
   hal_pin_inst_t enu;
   hal_pin_inst_t env;
   hal_pin_inst_t enw;
};

struct dq_sp_pin_ctx_t{ // found in shared/comps/dq_sp.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t mode;
   hal_pin_inst_t pos;
   hal_pin_inst_t polecount;
   hal_pin_inst_t a;
   hal_pin_inst_t b;
   hal_pin_inst_t d;
   hal_pin_inst_t q;
};

struct idq_pin_ctx_t{ // found in shared/comps/idq.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t mode;
   hal_pin_inst_t d;
   hal_pin_inst_t q;
   hal_pin_inst_t pos;
   hal_pin_inst_t polecount;
   hal_pin_inst_t a;
   hal_pin_inst_t b;
   hal_pin_inst_t u;
   hal_pin_inst_t v;
   hal_pin_inst_t w;
};

struct pole_pin_ctx_t{ // found in shared/comps/pole.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t pos;
   hal_pin_inst_t cpos;
   hal_pin_inst_t p;
};

struct map_pin_ctx_t{ // found in shared/comps/map.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t pos_in;
   hal_pin_inst_t pos_out;
   hal_pin_inst_t pos_out2;
   hal_pin_inst_t start;
   hal_pin_inst_t freq;
   hal_pin_inst_t over;
   hal_pin_inst_t print;
   hal_pin_inst_t state;
   hal_pin_inst_t counter;
   hal_pin_inst_t index;
   hal_pin_inst_t m[50];
};

struct vel_pin_ctx_t{ // found in shared/comps/vel.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t pos_in;
   hal_pin_inst_t pos_out;
   hal_pin_inst_t vel;
   hal_pin_inst_t acc;
   hal_pin_inst_t w;
   hal_pin_inst_t d;
   hal_pin_inst_t g;
   hal_pin_inst_t h;
   hal_pin_inst_t j;
   hal_pin_inst_t lp;
   hal_pin_inst_t torque;
   hal_pin_inst_t vel_ff;
   hal_pin_inst_t en;
   hal_pin_inst_t pos_error;
};

struct rl_pin_ctx_t{ // found in shared/comps/rl.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t ra;
   hal_pin_inst_t rb;
   hal_pin_inst_t ld;
   hal_pin_inst_t lq;
   hal_pin_inst_t la;
   hal_pin_inst_t lb;
   hal_pin_inst_t max_cur;
   hal_pin_inst_t udc;
   hal_pin_inst_t start;
   hal_pin_inst_t state;
   hal_pin_inst_t ki;
   hal_pin_inst_t time;
   hal_pin_inst_t t;
   hal_pin_inst_t ia_fb;
   hal_pin_inst_t ib_fb;
   hal_pin_inst_t ua_fb;
   hal_pin_inst_t ub_fb;
   hal_pin_inst_t ua;
   hal_pin_inst_t ub;
};

struct ypid_pin_ctx_t{ // found in shared/comps/ypid.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t pos_ext_cmd;
   hal_pin_inst_t pos_fb;
   hal_pin_inst_t pos_error;
   hal_pin_inst_t vel_ext_cmd;
   hal_pin_inst_t vel_fb;
   hal_pin_inst_t vel_cmd;
   hal_pin_inst_t vel_error;
   hal_pin_inst_t vel_min;
   hal_pin_inst_t enable;
   hal_pin_inst_t out;
   hal_pin_inst_t pos_p;
   hal_pin_inst_t vel_p;
   hal_pin_inst_t vel_i;
   hal_pin_inst_t vel_ff;
   hal_pin_inst_t max_vel;
   hal_pin_inst_t max_acc;
   hal_pin_inst_t max_out;
   hal_pin_inst_t vel_sat;
   hal_pin_inst_t out_sat;
   hal_pin_inst_t saturated;
};

extern const hal_comp_t * comps[];
extern const pin_t pins[];
extern const uint32_t comp_count;
extern const uint32_t pin_count;

extern const hal_comp_t hv_comp_struct; // found in stmsp/stm32f303/src/comps/hv.c
extern const hal_comp_t io_comp_struct; // found in stmsp/stm32f303/src/comps/io.c
extern const hal_comp_t tle_comp_struct; // found in stmsp/stm32f303/src/comps/tle.c
extern const hal_comp_t sim_comp_struct; // found in shared/comps/sim.c
extern const hal_comp_t term_comp_struct; // found in shared/comps/term.c
extern const hal_comp_t curpid_comp_struct; // found in shared/comps/curpid.c
extern const hal_comp_t svm_comp_struct; // found in shared/comps/svm.c
extern const hal_comp_t dq_sp_comp_struct; // found in shared/comps/dq_sp.c
extern const hal_comp_t idq_comp_struct; // found in shared/comps/idq.c
extern const hal_comp_t pole_comp_struct; // found in shared/comps/pole.c
extern const hal_comp_t map_comp_struct; // found in shared/comps/map.c
extern const hal_comp_t vel_comp_struct; // found in shared/comps/vel.c
extern const hal_comp_t rl_comp_struct; // found in shared/comps/rl.c
extern const hal_comp_t ypid_comp_struct; // found in shared/comps/ypid.c
