HAL_COMP(clarke);

#define SQRT3 1.732050808

HAL_PIN(a) = 0;
HAL_PIN(b) = 0;
HAL_PIN(y) = 0;

HAL_PIN(u);
HAL_PIN(v);
HAL_PIN(w);


RT(
   float u = PIN(u);
   float v = PIN(v);
   float w = PIN(w);

   PIN(a) = 2.0 / 3.0 * u -   1.0 / 3.0 * v -   1.0 / 3.0 * w;
   PIN(b) =       0.0 * u + SQRT3 / 3.0 * v - SQRT3 / 3.0 * w;
   PIN(y) = 1.0 / 3.0 * u +   1.0 / 3.0 * v +   1.0 / 3.0 * w;
);

ENDCOMP;
