COMP(test);

HAL_PIN(test0) = 0.0;
HAL_PIN(test1) = 0.0;
HAL_PIN(test2) = 0.0;
HAL_PIN(start) = 0.0;

RT_CALC(
  HT(
    GOTO(0);
    STATE(0){
      PIN(test0) = 1.0;
      PIN(test1) = 0.0;
      PIN(test2) = 0.0;

      if(PIN(start) > 0.0){
        GOTO(1);
      }
    }
    STATE(1){
      PIN(test0) = 0.0;
      PIN(test1) = 1.0;
      PIN(test2) = 0.0;
      SLEEP(0.5);
      PIN(test0) = 0.0;
      PIN(test1) = 0.0;
      PIN(test2) = 2.0;
      SLEEP(0.5);
      GOTO(0);
    }
  );
);


ENDCOMP;
