//generated by tools/create_config.py DO NOT EDIT

#include "config.h"

const uint32_t num_of_config_templates = 33;

config_template_t config_templates[] = {
{
.name = "acim",
.config = "\
load acim_ttc\n\
acim_ttc0.rt_prio = 9\n\
pid0.max_torque = acim_ttc0.t_max\n\
pid0.min_torque = acim_ttc0.t_min\n\
pid0.max_vel = conf0.max_vel\n\
acim_ttc0.torque = pid0.torque_cor_cmd\n\
acim_ttc0.polecount = conf0.polecount\n\
acim_ttc0.vel_m = vel1.vel\n\
acim_ttc0.mode = 0\n\
acim_ttc0.sensorless = 0\n\
hv0.q_cmd = acim_ttc0.q_cmd\n\
hv0.d_cmd = acim_ttc0.d_cmd\n\
hv0.cmd_mode = acim_ttc0.cmd_mode\n\
hv0.phase_mode = 2\n\
hv0.pos = acim_ttc0.pos\n\
"
},

{
.name = "com_test",
.config = "\
fb_switch0.en = 1\n\
term0.wave0 = sim0.vel\n\
term0.wave1 = fb_switch0.com_fb_no_offset\n\
term0.wave2 = fb_switch0.mot_abs_fb_no_offset\n\
term0.wave3 = fb_switch0.com_fb\n\
term0.gain2 = 20.000000\n\
term0.gain3 = 20.000000\n\
hv0.pos = sim0.vel\n\
hv0.d_cmd = 1.000000\n\
hv0.en = 1.000000\n\
conf0.max_pos_error = 0\n\
"
},

{
.name = "conf",
.config = "\
load conf\n\
conf0.r = 1\n\
conf0.l = 0.01\n\
conf0.j = 0.000025\n\
conf0.j_load = 0.0\n\
conf0.j_lpf = 100.0\n\
conf0.psi = 0.055\n\
conf0.polecount = 2\n\
conf0.mot_fb_polecount = 1\n\
conf0.mot_fb_res = 16384\n\
conf0.com_fb_polecount = 1\n\
conf0.com_fb_res = 16384\n\
conf0.joint_fb_polecount = 1\n\
conf0.joint_fb_res = 16384\n\
conf0.high_mot_temp = 80\n\
conf0.max_mot_temp = 100\n\
conf0.phase_time = 0.5\n\
conf0.phase_cur = 1\n\
conf0.max_vel = 800\n\
conf0.max_acc = 80000\n\
conf0.max_force = 1\n\
conf0.max_dc_cur = 15\n\
conf0.max_ac_cur = 4\n\
conf0.cmd_res = 16384\n\
conf0.max_dc_volt = 380\n\
conf0.max_hv_temp = 90\n\
conf0.max_pos_error = 1.5\n\
conf0.high_dc_volt = 350\n\
conf0.low_dc_volt = 24\n\
conf0.high_hv_temp = 70\n\
conf0.fan_hv_temp = 50\n\
conf0.g = 0.99\n\
conf0.pos_p = 100\n\
conf0.vel_p = 2000\n\
conf0.vel_i = 5\n\
conf0.vel_g = 1\n\
conf0.cur_p = 0.2\n\
conf0.cur_i = 1.5\n\
conf0.max_sat = 0.2\n\
"
},

{
.name = "dc",
.config = "\
load dc_limits\n\
load dc_ttc\n\
dc_limits0.rt_prio = 7\n\
dc_ttc0.rt_prio = 9\n\
dc_limits0.r = conf0.r\n\
dc_limits0.ld = conf0.l\n\
dc_limits0.lq = conf0.l\n\
dc_limits0.psi = conf0.psi\n\
dc_ttc0.psi = conf0.psi\n\
dc_limits0.ac_volt = hv0.pwm_volt\n\
dc_limits0.iq = hv0.iq_fb\n\
pid0.max_torque = dc_limits0.max_torque\n\
pid0.min_torque = dc_limits0.min_torque\n\
pid0.max_vel = dc_limits0.abs_max_vel\n\
dc_ttc0.torque = pid0.torque_cor_cmd\n\
hv0.d_cmd = 0\n\
hv0.pos = 0\n\
hv0.phase_mode = 3\n\
hv0.q_cmd = dc_ttc0.cur\n\
hv0.cmd_mode = 1\n\
"
},

{
.name = "en",
.config = "\
load en\n\
en0.rt_prio = 2\n\
en0.en_in = 1\n\
fault0.en = en0.en_out0\n\
en0.fault = fault0.fault\n\
en0.time = 1\n\
"
},

{
.name = "enc_cmd",
.config = "\
load enc_cmd\n\
enc_cmd0.rt_prio = 2\n\
enc_cmd0.res = conf0.cmd_res\n\
rev0.in = enc_cmd0.pos\n\
fault0.cmd_error = 0\n\
io0.cmdg = 1\n\
"
},

{
.name = "enc_fb0",
.config = "\
load enc_fb\n\
enc_fb0.rt_prio = 2\n\
enc_fb0.res = conf0.mot_fb_res\n\
enc_fb0.sin = adc0.sin0l\n\
enc_fb0.cos = adc0.cos0l\n\
enc_fb0.quad = adc0.quad\n\
fb_switch0.mot_pos = enc_fb0.pos\n\
fb_switch0.mot_abs_pos = enc_fb0.abs_pos\n\
fb_switch0.mot_polecount = 1\n\
fb_switch0.mot_state = enc_fb0.state\n\
fault0.mot_fb_error = enc_fb0.error\n\
io0.fb0y = enc_fb0.error\n\
io0.fb0g = 1\n\
enc_fb0.vel = vel1.vel\n\
enc_fb0.amp = adc0.amp0\n\
enc_fb0.en_index = 1\n\
"
},

{
.name = "encdmm_fb0",
.config = "\
load dmm\n\
dmm0.rt_prio = 2\n\
fb_switch0.mot_pos = dmm0.pos\n\
fb_switch0.mot_abs_pos = dmm0.pos\n\
fb_switch0.mot_polecount = conf0.mot_fb_polecount\n\
fb_switch0.mot_state = 3\n\
fault0.mot_fb_error = dmm0.error\n\
io0.fb0y = dmm0.error\n\
io0.fb0g = 1\n\
"
},

{
.name = "encm_fb0",
.config = "\
load encm\n\
encm0.rt_prio = 2\n\
fb_switch0.mot_pos = encm0.pos\n\
fb_switch0.mot_abs_pos = encm0.pos\n\
fb_switch0.mot_polecount = conf0.mot_fb_polecount\n\
fb_switch0.mot_state = encm0.state\n\
fault0.mot_fb_error = encm0.error\n\
io0.fb0y = encm0.error\n\
io0.fb0g = 1\n\
"
},

{
.name = "encs_fb0",
.config = "\
load encs\n\
encs0.rt_prio = 2\n\
fb_switch0.mot_pos = encs0.pos\n\
fb_switch0.mot_abs_pos = encs0.pos\n\
fb_switch0.mot_polecount = conf0.mot_fb_polecount\n\
fb_switch0.mot_state = encs0.state\n\
fault0.mot_fb_error = encs0.error\n\
io0.fb0y = encs0.error\n\
io0.fb0g = 1\n\
"
},

{
.name = "encws_fb0",
.config = "\
link enc_fb0\n\
link uvw_fb0\n\
uvw0.mode = 1\n\
enc_fb0.en_index = 0\n\
"
},

{
.name = "fanuc_fb0",
.config = "\
load encf\n\
encf0.rt_prio = 1\n\
fb_switch0.com_pos = encf0.com_pos\n\
fb_switch0.com_abs_pos = encf0.com_pos\n\
fb_switch0.com_state = 3\n\
fb_switch0.com_polecount = conf0.com_fb_polecount\n\
conf0.com_fb_polecount = conf0.polecount\n\
fb_switch0.mot_pos = encf0.pos\n\
fb_switch0.mot_abs_pos = encf0.abs_pos\n\
fb_switch0.mot_state = encf0.state\n\
fault0.mot_fb_error = encf0.error\n\
fb_switch0.mot_polecount = 1\n\
conf0.mot_fb_res = 1048576\n\
io0.fb0y = encf0.error\n\
io0.fb0g = 1\n\
"
},

{
.name = "fanuc_io",
.config = "\
load fanuc\n\
fanuc0.rt_prio = 2\n\
fanuc0.C2 = io0.CTX\n\
fanuc0.C1 = io0.C12\n\
fanuc0.C4 = io0.CRX\n\
fanuc0.C8 = io0.C54\n\
io0.cmd_remap = 1\n\
fb_switch0.com_pos = fanuc0.pos\n\
fb_switch0.com_abs_pos = fanuc0.pos\n\
fb_switch0.com_state = fanuc0.state\n\
fb_switch0.com_polecount = conf0.com_fb_polecount\n\
"
},

{
.name = "hx",
.config = "\
load hx\n\
hx0.rt_prio = 1.5\n\
hx0.gain = 100\n\
"
},

{
.name = "jog_cmd",
.config = "\
load jog\n\
load stp\n\
jog0.rt_prio = 2\n\
stp0.rt_prio = 2.1\n\
stp0.jog = jog0.jog\n\
rev0.in = stp0.mpos\n\
fault0.cmd_error = 0\n\
"
},

{
.name = "linkv3",
.config = "\
load pmsm\n\
load pmsm_limits\n\
load pmsm_ttc\n\
load idq\n\
load curpid\n\
\n\
hv0.a = idq0.a\n\
hv0.b = idq0.b\n\
hv0.iq = pmsm0.iq\n\
hv0.enable = fault0.en_pid\n\
\n\
pmsm0.rt_prio = 11\n\
pmsm0.ud = curpid0.ud\n\
pmsm0.uq = curpid0.uq\n\
pmsm0.vel = net0.fb_d\n\
pmsm0.r = conf0.r\n\
pmsm0.ld = conf0.l\n\
pmsm0.lq = conf0.l\n\
pmsm0.psi = conf0.psi\n\
pmsm0.polecount = conf0.polecount\n\
\n\
idq0.rt_prio = 13.0\n\
idq0.mode = 2\n\
idq0.pos = vel2.pos_out\n\
idq0.polecount = 1\n\
idq0.d = curpid0.ud\n\
idq0.q = curpid0.uq\n\
\n\
curpid0.rt_prio = 10\n\
curpid0.en = fault0.en_pid\n\
curpid0.id_fb = pmsm0.id\n\
curpid0.iq_fb = pmsm0.iq\n\
curpid0.id_cmd = fb_switch0.id\n\
curpid0.iq_cmd = pmsm_ttc0.cur\n\
curpid0.dc_volt = hv0.dc_volt\n\
curpid0.ac_volt = hv0.ac_volt\n\
curpid0.r = conf0.r\n\
curpid0.ld = conf0.l\n\
curpid0.lq = conf0.l\n\
curpid0.ff = conf0.cur_ff\n\
curpid0.kp = conf0.cur_p\n\
curpid0.ki = conf0.cur_i\n\
curpid0.kind = conf0.cur_ind\n\
curpid0.cmd_mode = 1\n\
curpid0.pwm_volt = hv0.pwm_volt\n\
\n\
\n\
pmsm_ttc0.rt_prio = 9\n\
pmsm_ttc0.torque = pid0.torque_cor_cmd\n\
pmsm_ttc0.polecount = conf0.polecount\n\
pmsm_ttc0.psi = conf0.psi\n\
\n\
fb_switch0.phase_cur = conf0.phase_cur\n\
fb_switch0.phase_time = conf0.phase_time\n\
\n\
\n\
pid0.min_torque = pmsm_limits0.next_min_torque\n\
pid0.max_torque = pmsm_limits0.next_max_torque\n\
"
},

{
.name = "misc",
.config = "\
term0.wave0 = reslimit0.pos_out\n\
term0.wave1 = fb_switch0.plot_fb_pos\n\
term0.wave2 = vel0.vel\n\
term0.wave3 = vel1.vel\n\
term0.gain0 = 20\n\
term0.gain1 = 20\n\
term0.gain2 = 1\n\
term0.gain3 = 1\n\
"
},

{
.name = "mpid",
.config = "\
load adc\n\
load reslimit\n\
load rev\n\
load fb_switch\n\
load veltime\n\
load veltime\n\
load vel\n\
load mpid\n\
load fault\n\
load hv\n\
load sim\n\
load io\n\
load iit\n\
link conf\n\
hv0.rt_prio = 0.9\n\
hv0.frt_prio = 1\n\
adc0.rt_prio = 1\n\
reslimit0.rt_prio = 3\n\
rev0.rt_prio = 4\n\
fb_switch0.rt_prio = 5\n\
veltime0.frt_prio = 6\n\
veltime1.frt_prio = 6\n\
vel0.rt_prio = 6\n\
io0.rt_prio = 7\n\
mpid0.rt_prio = 8\n\
fault0.rt_prio = 10\n\
iit0.rt_prio = 13\n\
sim0.rt_prio = 13\n\
term0.rt_prio = 16\n\
rev0.rev = conf0.cmd_rev\n\
fb_switch0.mot_rev = conf0.mot_fb_rev\n\
fb_switch0.com_rev = conf0.com_fb_rev\n\
fb_switch0.joint_rev = conf0.joint_fb_rev\n\
reslimit0.res = conf0.mot_fb_res\n\
mpid0.j = conf0.j\n\
mpid0.pos_p = conf0.pos_p\n\
mpid0.vel_p = conf0.vel_p\n\
mpid0.vel_i = conf0.vel_i\n\
mpid0.max_vel = conf0.max_vel\n\
mpid0.max_acc = conf0.max_acc\n\
mpid0.max_torque = conf0.max_force\n\
fault0.max_sat = conf0.max_sat\n\
fault0.max_pos_error = conf0.max_pos_error\n\
fault0.max_vel_error = conf0.max_vel_error\n\
fault0.max_dc_cur = conf0.max_dc_cur\n\
fault0.max_ac_cur = conf0.max_ac_cur\n\
fault0.max_dc_volt = conf0.max_dc_volt\n\
fault0.high_dc_volt = conf0.max_dc_volt\n\
fault0.min_dc_volt = conf0.min_dc_volt\n\
fault0.max_hv_temp = conf0.max_hv_temp\n\
fault0.max_mot_temp = conf0.max_mot_temp\n\
fault0.high_hv_temp = conf0.high_hv_temp\n\
fault0.high_mot_temp = conf0.high_mot_temp\n\
fault0.fan_hv_temp = conf0.fan_hv_temp\n\
fault0.fan_mot_temp = conf0.fan_mot_temp\n\
fault0.ac_cur = hv0.abs_cur\n\
hv0.rev = conf0.out_rev\n\
hv0.r = conf0.r\n\
hv0.l = conf0.l\n\
hv0.psi = conf0.psi\n\
hv0.cur_p = conf0.cur_p\n\
hv0.cur_i = conf0.cur_i\n\
hv0.cur_ff = conf0.cur_ff\n\
hv0.cur_ind = conf0.cur_ind\n\
hv0.max_cur = conf0.max_ac_cur\n\
reslimit0.pos_in = rev0.out\n\
fb_switch0.cmd_pos = reslimit0.pos_out\n\
fb_switch0.polecount = conf0.polecount\n\
fb_switch0.en = fault0.en_fb\n\
fb_switch0.mot_polecount = conf0.mot_fb_polecount\n\
fb_switch0.joint_polecount = conf0.joint_fb_polecount\n\
fb_switch0.com_polecount = conf0.com_fb_polecount\n\
fb_switch0.mot_offset = conf0.mot_fb_offset\n\
fb_switch0.joint_offset = conf0.joint_fb_offset\n\
fb_switch0.com_offset = conf0.com_fb_offset\n\
fb_switch0.phase_time = conf0.phase_time\n\
fb_switch0.phase_cur = conf0.phase_cur\n\
veltime0.pos = rev0.out\n\
veltime1.pos = fb_switch0.vel_fb\n\
vel0.pos_in = fb_switch0.com_fb\n\
vel0.en = fault0.en_fb\n\
vel0.torque = mpid0.torque_cor_cmd\n\
mpid0.en = fault0.en_pid\n\
mpid0.pos_ext_cmd = reslimit0.pos_out\n\
mpid0.vel_ext_cmd = veltime0.vel_lp\n\
mpid0.pos_fb = fb_switch0.pos_fb\n\
mpid0.vel_fb = veltime1.vel_lp\n\
rev0.in_d = veltime0.vel_lp\n\
fault0.pos_error = mpid0.pos_error\n\
fault0.vel_error = mpid0.vel_error\n\
fault0.dc_volt = hv0.dc_volt\n\
fault0.hv_temp = hv0.hv_temp\n\
fault0.dc_cur = hv0.dc_cur\n\
fault0.hv_error = hv0.fault\n\
fault0.fb_ready = fb_switch0.state\n\
hv0.en = fault0.en_out\n\
hv0.pos = vel2.pos_out\n\
hv0.vel = vel2.vel\n\
hv0.scale = fault0.scale\n\
io0.fan = fault0.hv_fan\n\
io0.fault = fault0.fault\n\
io0.state = fault0.state\n\
pe0.udc = hv0.dc_volt\n\
pe0.idc = 0\n\
pe0.ud = 0\n\
pe0.uq = 0\n\
pe0.id = hv0.id_fb\n\
pe0.iq = hv0.iq_fb\n\
pe0.torque = mpid0.torque_cmd\n\
pe0.vel = vel1.vel\n\
pe0.r = conf0.r\n\
pe0.j = conf0.j\n\
pe0.cap = 0.00054\n\
iit0.max_temp = conf0.max_mot_temp\n\
iit0.high_temp = conf0.high_mot_temp\n\
iit0.max_cur = conf0.max_ac_cur\n\
fault0.mot_temp = iit0.temp\n\
iit0.cur = hv0.abs_cur\n\
"
},

{
.name = "mpmsm",
.config = "\
load pmsm_ttc\n\
pmsm_ttc0.rt_prio = 9\n\
pmsm_ttc0.psi = conf0.psi\n\
pmsm_ttc0.polecount = conf0.polecount\n\
pmsm_ttc0.pos_in = vel0.pos_out\n\
pmsm_ttc0.torque = mpid0.torque_cmd\n\
hv0.d_cmd = fb_switch0.id\n\
hv0.q_cmd = pmsm_ttc0.cur\n\
hv0.cmd_mode = 1\n\
hv0.phase_mode = 2\n\
hv0.pos = pmsm_ttc0.pos_out\n\
"
},

{
.name = "pid",
.config = "\
load adc\n\
load reslimit\n\
load rev\n\
load fb_switch\n\
load vel\n\
load vel\n\
load vel\n\
load pid\n\
load fault\n\
load hv\n\
load sim\n\
load io\n\
load iit\n\
link conf\n\
hv0.rt_prio = 0.9\n\
adc0.rt_prio = 1\n\
reslimit0.rt_prio = 3\n\
rev0.rt_prio = 4\n\
fb_switch0.rt_prio = 5\n\
vel0.rt_prio = 6\n\
vel1.rt_prio = 6\n\
vel2.rt_prio = 6\n\
io0.rt_prio = 7\n\
io0.frt_prio = 3\n\
pid0.rt_prio = 8\n\
fault0.rt_prio = 10\n\
iit0.rt_prio = 13\n\
sim0.rt_prio = 13\n\
term0.rt_prio = 16\n\
rev0.rev = conf0.cmd_rev\n\
fb_switch0.mot_rev = conf0.mot_fb_rev\n\
fb_switch0.com_rev = conf0.com_fb_rev\n\
fb_switch0.joint_rev = conf0.joint_fb_rev\n\
reslimit0.res = conf0.mot_fb_res\n\
vel1.j = conf0.j\n\
vel2.j = conf0.j\n\
pid0.j_mot = conf0.j\n\
pid0.j_load = conf0.j_load\n\
pid0.j_lpf = conf0.j_lpf\n\
pid0.pos_p = conf0.pos_p\n\
pid0.vel_p = conf0.vel_p\n\
pid0.vel_i = conf0.vel_i\n\
pid0.vel_g = conf0.vel_g\n\
pid0.acc_g = conf0.acc_g\n\
pid0.g = conf0.g\n\
pid0.max_usr_vel = conf0.max_vel\n\
pid0.max_usr_acc = conf0.max_acc\n\
pid0.max_usr_torque = conf0.max_force\n\
fault0.max_sat = conf0.max_sat\n\
fault0.max_pos_error = conf0.max_pos_error\n\
fault0.max_vel_error = conf0.max_vel_error\n\
fault0.max_dc_cur = conf0.max_dc_cur\n\
fault0.max_ac_cur = conf0.max_ac_cur\n\
fault0.max_dc_volt = conf0.max_dc_volt\n\
fault0.high_dc_volt = conf0.high_dc_volt\n\
fault0.min_dc_volt = conf0.min_dc_volt\n\
fault0.max_hv_temp = conf0.max_hv_temp\n\
fault0.max_mot_temp = conf0.max_mot_temp\n\
fault0.high_hv_temp = conf0.high_hv_temp\n\
fault0.high_mot_temp = conf0.high_mot_temp\n\
fault0.fan_hv_temp = conf0.fan_hv_temp\n\
fault0.fan_mot_temp = conf0.fan_mot_temp\n\
fault0.ac_cur = hv0.abs_cur\n\
hv0.rev = conf0.out_rev\n\
hv0.r = conf0.r\n\
hv0.l = conf0.l\n\
hv0.psi = conf0.psi\n\
hv0.cur_p = conf0.cur_p\n\
hv0.cur_i = conf0.cur_i\n\
hv0.cur_ff = conf0.cur_ff\n\
hv0.cur_ind = conf0.cur_ind\n\
hv0.max_cur = conf0.max_ac_cur\n\
reslimit0.pos_in = rev0.out\n\
fb_switch0.cmd_pos = reslimit0.pos_out\n\
fb_switch0.polecount = conf0.polecount\n\
fb_switch0.en = fault0.en_fb\n\
fb_switch0.mot_polecount = conf0.mot_fb_polecount\n\
fb_switch0.joint_polecount = conf0.joint_fb_polecount\n\
fb_switch0.com_polecount = conf0.com_fb_polecount\n\
fb_switch0.mot_offset = conf0.mot_fb_offset\n\
fb_switch0.joint_offset = conf0.joint_fb_offset\n\
fb_switch0.com_offset = conf0.com_fb_offset\n\
fb_switch0.phase_time = conf0.phase_time\n\
fb_switch0.phase_cur = conf0.phase_cur\n\
vel0.pos_in = rev0.out\n\
vel0.en = fault0.en_fb\n\
vel1.pos_in = fb_switch0.vel_fb\n\
vel1.en = fault0.en_fb\n\
vel1.torque = pid0.torque_cmd\n\
vel2.pos_in = fb_switch0.com_fb\n\
vel2.en = fault0.en_fb\n\
vel2.torque = pid0.torque_cmd\n\
pid0.enable = fault0.en_pid\n\
pid0.pos_ext_cmd = reslimit0.pos_out\n\
pid0.vel_ext_cmd = vel0.vel\n\
pid0.pos_fb = fb_switch0.pos_fb\n\
pid0.vel_fb = vel1.vel\n\
rev0.in_d = vel0.vel\n\
fault0.pos_error = pid0.pos_error\n\
fault0.vel_error = pid0.vel_error\n\
fault0.sat = pid0.saturated\n\
fault0.dc_volt = hv0.dc_volt\n\
fault0.hv_temp = hv0.hv_temp\n\
fault0.dc_cur = hv0.dc_cur\n\
fault0.hv_error = hv0.fault\n\
fault0.fb_ready = fb_switch0.state\n\
hv0.en = fault0.en_out\n\
hv0.pos = vel2.pos_out\n\
hv0.vel = vel2.vel\n\
hv0.scale = fault0.scale\n\
io0.fan = fault0.hv_fan\n\
io0.fault = fault0.fault\n\
io0.state = fault0.state\n\
pe0.udc = hv0.dc_volt\n\
pe0.idc = 0\n\
pe0.ud = 0\n\
pe0.uq = 0\n\
pe0.id = hv0.id_fb\n\
pe0.iq = hv0.iq_fb\n\
pe0.torque = pid0.torque_cor_cmd\n\
pe0.vel = vel1.vel\n\
pe0.r = conf0.r\n\
pe0.j = conf0.j\n\
pe0.cap = 0.00054\n\
iit0.max_temp = conf0.max_mot_temp\n\
iit0.high_temp = conf0.high_mot_temp\n\
iit0.max_cur = conf0.max_ac_cur\n\
fault0.mot_temp = iit0.temp\n\
iit0.cur = hv0.abs_cur\n\
"
},

{
.name = "pmsm",
.config = "\
load pmsm_limits\n\
load pmsm_ttc\n\
pmsm_limits0.rt_prio = 7\n\
pmsm_ttc0.rt_prio = 9\n\
pmsm_limits0.r = conf0.r\n\
pmsm_limits0.ld = conf0.l\n\
pmsm_limits0.lq = conf0.l\n\
pmsm_limits0.psi = conf0.psi\n\
pmsm_limits0.j = conf0.j\n\
pmsm_limits0.polecount = conf0.polecount\n\
pmsm_ttc0.psi = conf0.psi\n\
pmsm_ttc0.polecount = conf0.polecount\n\
pmsm_limits0.ac_volt = hv0.pwm_volt\n\
pmsm_limits0.iq = hv0.iq_fb\n\
pmsm_limits0.id = hv0.id_fb\n\
pmsm_ttc0.pos_in = vel2.pos_out\n\
pid0.max_torque = pmsm_limits0.max_torque\n\
pid0.min_torque = pmsm_limits0.min_torque\n\
pid0.max_vel = pmsm_limits0.abs_max_vel\n\
pmsm_ttc0.torque = pid0.torque_cor_cmd\n\
hv0.d_cmd = fb_switch0.id\n\
hv0.q_cmd = pmsm_ttc0.cur\n\
hv0.cmd_mode = 1\n\
hv0.phase_mode = 2\n\
hv0.pos = pmsm_ttc0.pos_out\n\
"
},

{
.name = "pos_filter",
.config = "\
load pos_filter\n\
pos_filter-1.rt_prio = 6\n\
vel0.rt_prio = 0\n\
pos_filter-1.en = fault0.en_fb\n\
pos_filter-1.pos_in = rev0.out\n\
pos_filter-1.vel_in = rev0.out_d\n\
pos_filter-1.bandwidth = 1000\n\
term0.wave2 = pos_filter-1.vel_out\n\
reslimit0.pos_in = pos_filter-1.pos_out\n\
pid0.vel_ext_cmd = pos_filter-1.vel_out\n\
pid0.acc_ext_cmd = pos_filter-1.acc_out\n\
"
},

{
.name = "psi",
.config = "\
load psi\n\
psi0.rt_prio = 10\n\
psi0.dc_volt = hv0.dc_volt\n\
psi0.vel = net0.fb_d\n\
psi0.polecount = conf0.polecount\n\
net0.enable = 0\n\
vel1.en = 1\n\
io0.brake = 1\n\
term0.wave0 = psi0.psi\n\
term0.wave1 = psi0.max_psi\n\
term0.gain0 = 500\n\
term0.gain1 = 500\n\
"
},

{
.name = "res_fb0",
.config = "\
load res\n\
res0.rt_prio = 2\n\
res0.sin = adc0.sin0\n\
res0.cos = adc0.cos0\n\
adc0.res_mode = res0.res_mode\n\
res0.quad = adc0.quad\n\
res0.poles = conf0.mot_fb_polecount\n\
fb_switch0.mot_pos = res0.pos\n\
fb_switch0.mot_abs_pos = res0.pos\n\
fb_switch0.mot_polecount = conf0.mot_fb_polecount\n\
fb_switch0.mot_state = res0.state\n\
fault0.mot_fb_error = res0.error\n\
res0.vel = fb_switch0.mot_vel\n\
io0.fb0y = res0.error\n\
io0.fb0g = 1\n\
"
},

{
.name = "rl",
.config = "\
link pid\n\
link pmsm\n\
conf0.max_ac_cur = 15\n\
load rl\n\
rl0.rt_prio = 6\n\
hv0.en = rl0.en_out\n\
hv0.d_cmd = rl0.ud_cmd\n\
hv0.q_cmd = rl0.uq_cmd\n\
rl0.id_fb = hv0.id_fb\n\
rl0.iq_fb = hv0.iq_fb\n\
rl0.ud_fb = hv0.ud_fb\n\
rl0.uq_fb = hv0.uq_fb\n\
hv0.cmd_mode = 0\n\
hv0.pos = 0\n\
term0.wave0 = rl0.ud_cmd\n\
term0.wave1 = hv0.id_fb\n\
term0.wave2 = rl0.r\n\
term0.wave3 = rl0.ld\n\
term0.gain0 = 5\n\
term0.gain1 = 5\n\
term0.gain2 = 30\n\
term0.gain3 = 3000\n\
"
},

{
.name = "smartabs_fb0",
.config = "\
load smartabs\n\
smartabs0.rt_prio = 0.8\n\
fb_switch0.mot_pos = smartabs0.pos\n\
fb_switch0.mot_abs_pos = smartabs0.pos\n\
fb_switch0.mot_polecount = conf0.mot_fb_polecount\n\
fb_switch0.mot_state = smartabs0.state\n\
fault0.mot_fb_error = smartabs0.error\n\
io0.fb0y = smartabs0.error\n\
io0.fb0g = 1\n\
"
},

{
.name = "sserial",
.config = "\
load sserial\n\
load vel_int\n\
load linrev\n\
load idx_home\n\
sserial0.rt_prio = 2.0\n\
sserial0.frt_prio = 2.0\n\
linrev0.rt_prio = 2.1\n\
vel_int0.rt_prio = 2.2\n\
idx_home0.rt_prio = 2.3\n\
linrev0.cmd_in = sserial0.pos_cmd\n\
linrev0.cmd_d_in = sserial0.pos_cmd_d\n\
vel_int0.pos_in = linrev0.cmd_out\n\
vel_int0.vel_in = linrev0.cmd_d_out\n\
fault0.en = sserial0.enable\n\
sserial0.fault = fault0.fault\n\
fault0.cmd_error = sserial0.error\n\
linrev0.fb_in = idx_home0.pos_out\n\
linrev0.fb_d_in = vel1.vel\n\
idx_home0.fb = fb_switch0.mot_fb_no_offset\n\
idx_home0.fb_abs = fb_switch0.mot_abs_fb_no_offset\n\
idx_home0.index_en = sserial0.index_out\n\
idx_home0.mot_state = fb_switch0.mot_state\n\
sserial0.index_clear = idx_home0.index_clear\n\
linrev0.rev_clear = sserial0.index_clear\n\
sserial0.pos_fb = linrev0.fb_out\n\
sserial0.vel_fb = linrev0.fb_d_out\n\
sserial0.pos_advance = 0.0008\n\
rev0.in = vel_int0.pos_out\n\
rev0.in_d = vel_int0.vel_out\n\
pid0.vel_ext_cmd = rev0.out_d\n\
vel_int0.wd = 0.002\n\
vel0.en = 0\n\
velbuf0.rt_prio = 0\n\
io0.cmdy = sserial0.error\n\
io0.cmdg = 1\n\
sserial0.in0 = io0.ind0\n\
sserial0.in1 = io0.ind1\n\
io0.out0 = sserial0.out0\n\
io0.out1 = sserial0.out1\n\
io0.out2 = sserial0.out2\n\
fault0.brake_release = sserial0.out3\n\
term0.wave2 = linrev0.cmd_d_out\n\
sserial0.current = hv0.iq_fb\n\
linrev0.scale = sserial0.scale\n\
io0.clock_scale = sserial0.clock_scale\n\
"
},

{
.name = "sserial_dummy",
.config = "\
load sserial\n\
load vel_int\n\
load linrev\n\
load idx_home\n\
sserial0.rt_prio = 2.0\n\
sserial0.frt_prio = 2.0\n\
linrev0.rt_prio = 2.1\n\
vel_int0.rt_prio = 2.2\n\
idx_home0.rt_prio = 2.3\n\
linrev0.cmd_in = sserial0.pos_cmd\n\
linrev0.cmd_d_in = sserial0.pos_cmd_d\n\
vel_int0.pos_in = linrev0.cmd_out\n\
vel_int0.vel_in = linrev0.cmd_d_out\n\
linrev0.fb_in = linrev0.cmd_out\n\
linrev0.fb_d_in = linrev0.cmd_d_out\n\
sserial0.index_clear = idx_home0.index_clear\n\
linrev0.rev_clear = sserial0.index_clear\n\
sserial0.pos_fb = linrev0.fb_out\n\
sserial0.vel_fb = linrev0.fb_d_out\n\
sserial0.pos_advance = 0.0008\n\
pid0.vel_ext_cmd = rev0.out_d\n\
vel_int0.wd = 0.002\n\
io0.cmdy = sserial0.error\n\
io0.cmdg = 1\n\
linrev0.scale = 6\n\
"
},

{
.name = "sserial_uf",
.config = "\
load sserial\n\
sserial0.rt_prio = 2.0\n\
sserial0.frt_prio = 2.0\n\
fault0.en = sserial0.enable\n\
sserial0.fault = fault0.fault\n\
fault0.cmd_error = sserial0.error\n\
sserial0.vel_fb = avg0.out\n\
io0.cmdy = sserial0.error\n\
io0.cmdg = 1\n\
sserial0.in0 = io0.ind0\n\
sserial0.in1 = io0.ind1\n\
io0.out0 = sserial0.out0\n\
io0.out1 = sserial0.out1\n\
io0.out2 = sserial0.out2\n\
fault0.brake_release = sserial0.out3\n\
term0.wave2 = linrev0.cmd_d_out\n\
avg0.in = sserial0.pos_cmd_d\n\
sserial0.current = hv0.abs_cur\n\
"
},

{
.name = "uf",
.config = "\
load adc\n\
load fault\n\
load hv\n\
load sim\n\
load io\n\
load iit\n\
link conf\n\
load uf\n\
hv0.rt_prio = 0.9\n\
hv0.frt_prio = 1\n\
adc0.rt_prio = 1\n\
uf0.rt_prio = 6\n\
io0.rt_prio = 7\n\
fault0.rt_prio = 10\n\
iit0.rt_prio = 13\n\
sim0.rt_prio = 13\n\
term0.rt_prio = 16\n\
fault0.max_sat = conf0.max_sat\n\
fault0.max_pos_error = conf0.max_pos_error\n\
fault0.max_vel_error = conf0.max_vel_error\n\
fault0.max_dc_cur = conf0.max_dc_cur\n\
fault0.max_ac_cur = conf0.max_ac_cur\n\
fault0.max_dc_volt = conf0.max_dc_volt\n\
fault0.high_dc_volt = conf0.max_dc_volt\n\
fault0.min_dc_volt = conf0.min_dc_volt\n\
fault0.max_hv_temp = conf0.max_hv_temp\n\
fault0.max_mot_temp = conf0.max_mot_temp\n\
fault0.high_hv_temp = conf0.high_hv_temp\n\
fault0.high_mot_temp = conf0.high_mot_temp\n\
fault0.fan_hv_temp = conf0.fan_hv_temp\n\
fault0.fan_mot_temp = conf0.fan_mot_temp\n\
fault0.ac_cur = hv0.abs_cur\n\
hv0.rev = conf0.out_rev\n\
hv0.r = conf0.r\n\
hv0.l = conf0.l\n\
hv0.psi = conf0.psi\n\
hv0.cur_p = conf0.cur_p\n\
hv0.cur_i = conf0.cur_i\n\
hv0.cur_ff = conf0.cur_ff\n\
hv0.cur_ind = conf0.cur_ind\n\
hv0.max_cur = conf0.max_ac_cur\n\
uf0.polecount = conf0.polecount\n\
uf0.scale = fault0.scale\n\
uf0.cur = hv0.abs_cur\n\
hv0.pos = uf0.com_pos\n\
hv0.d_cmd = uf0.u_cmd\n\
hv0.cmd_mode = 0\n\
hv0.phase_mode = 2\n\
fault0.dc_volt = hv0.dc_volt\n\
fault0.hv_temp = hv0.hv_temp\n\
fault0.dc_cur = hv0.dc_cur\n\
fault0.hv_error = hv0.fault\n\
hv0.en = fault0.en_out\n\
hv0.scale = fault0.scale\n\
io0.fan = fault0.hv_fan\n\
io0.fault = fault0.fault\n\
io0.state = fault0.state\n\
iit0.max_temp = conf0.max_mot_temp\n\
iit0.high_temp = conf0.high_mot_temp\n\
iit0.max_cur = conf0.max_ac_cur\n\
fault0.mot_temp = iit0.temp\n\
iit0.cur = hv0.abs_cur\n\
"
},

{
.name = "uvw_fb0",
.config = "\
load uvw\n\
uvw0.rt_prio = 3\n\
uvw0.u = io0.fb0a\n\
uvw0.v = io0.fb0b\n\
uvw0.w = io0.fb0z\n\
\n\
uvw0.amp = adc0.amp0\n\
\n\
fb_switch0.com_pos = uvw0.pos\n\
fb_switch0.com_abs_pos = uvw0.pos\n\
fb_switch0.com_state = uvw0.state\n\
fb_switch0.com_polecount = conf0.com_fb_polecount\n\
conf0.com_fb_polecount = conf0.polecount\n\
fault0.com_fb_error = uvw0.error\n\
"
},

{
.name = "uvw_fb1",
.config = "\
load uvw\n\
uvw0.rt_prio = 2\n\
uvw0.u = io0.fb1a\n\
uvw0.v = io0.fb1b\n\
uvw0.w = io0.fb1z\n\
fb_switch0.com_pos = uvw0.pos\n\
fb_switch0.com_abs_pos = uvw0.pos\n\
fb_switch0.com_state = uvw0.state\n\
fb_switch0.com_polecount = conf0.com_fb_polecount\n\
io0.fb1g = 1\n\
io0.fb1y = uvw0.led\n\
conf0.com_fb_polecount = conf0.polecount\n\
uvw0.amp = adc0.amp1\n\
fault0.com_fb_error = uvw0.error\n\
"
},

{
.name = "velbuf",
.config = "\
load velbuf\n\
velbuf0.rt_prio = 6\n\
vel0.rt_prio = 0\n\
velbuf0.pos_in = rev0.out\n\
pid0.vel_ext_cmd = velbuf0.vel\n\
rev0.in_d = velbuf0.vel\n\
term0.wave2 = velbuf0.vel\n\
"
},

};
