#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct acim_ttc_pin_ctx_t{ // found in shared/comps/acim_ttc.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t mode;
   hal_pin_inst_t sensorless;
   hal_pin_inst_t torque_n;
   hal_pin_inst_t cur_n;
   hal_pin_inst_t slip_n;
   hal_pin_inst_t polecount;
   hal_pin_inst_t freq_n;
   hal_pin_inst_t vel_n;
   hal_pin_inst_t u_n;
   hal_pin_inst_t u_boost;
   hal_pin_inst_t t_boost;
   hal_pin_inst_t s_boost;
   hal_pin_inst_t torque;
   hal_pin_inst_t vel_m;
   hal_pin_inst_t d_cmd;
   hal_pin_inst_t q_cmd;
   hal_pin_inst_t cmd_mode;
   hal_pin_inst_t pos;
   hal_pin_inst_t vel_e;
   hal_pin_inst_t slip;
   hal_pin_inst_t t_min;
   hal_pin_inst_t t_max;
   hal_pin_inst_t scale;
   hal_pin_inst_t ki;
   hal_pin_inst_t duty;
   hal_pin_inst_t duty_setpoint;
};
