#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct dc_ttc_pin_ctx_t{ // found in shared/comps/dc_ttc.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t psi;
   hal_pin_inst_t torque;
   hal_pin_inst_t cur;
};
