#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct debounce_pin_ctx_t{ // found in shared/comps/debounce.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t in;
   hal_pin_inst_t out;
   hal_pin_inst_t debounce_time;
   hal_pin_inst_t timer;
};
