#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct en_pin_ctx_t{ // found in shared/comps/en.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t en_in;
   hal_pin_inst_t en_out0;
   hal_pin_inst_t en_out1;
   hal_pin_inst_t fault;
   hal_pin_inst_t time;
   hal_pin_inst_t timer;
};
