#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct fanuc_pin_ctx_t{ // found in shared/comps/fanuc.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t C1;
   hal_pin_inst_t C2;
   hal_pin_inst_t C4;
   hal_pin_inst_t C8;
   hal_pin_inst_t pos;
};
