#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct fault_pin_ctx_t{ // found in shared/comps/fault.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t en;
   hal_pin_inst_t state;
   hal_pin_inst_t fault;
   hal_pin_inst_t last_fault;
   hal_pin_inst_t en_out;
   hal_pin_inst_t en_fb;
   hal_pin_inst_t en_pid;
   hal_pin_inst_t fb_ready;
   hal_pin_inst_t cmd_error;
   hal_pin_inst_t mot_fb_error;
   hal_pin_inst_t com_fb_error;
   hal_pin_inst_t joint_fb_error;
   hal_pin_inst_t hv_error;
   hal_pin_inst_t hv_temp;
   hal_pin_inst_t mot_temp;
   hal_pin_inst_t max_hv_temp;
   hal_pin_inst_t max_mot_temp;
   hal_pin_inst_t high_hv_temp;
   hal_pin_inst_t high_mot_temp;
   hal_pin_inst_t fan_hv_temp;
   hal_pin_inst_t fan_mot_temp;
   hal_pin_inst_t scale;
   hal_pin_inst_t dc_volt;
   hal_pin_inst_t min_dc_volt;
   hal_pin_inst_t high_dc_volt;
   hal_pin_inst_t max_dc_volt;
   hal_pin_inst_t dc_cur;
   hal_pin_inst_t max_dc_cur;
   hal_pin_inst_t ac_cur;
   hal_pin_inst_t max_ac_cur;
   hal_pin_inst_t pos_error;
   hal_pin_inst_t max_pos_error;
   hal_pin_inst_t sat;
   hal_pin_inst_t max_sat;
   hal_pin_inst_t mot_brake;
   hal_pin_inst_t dc_brake;
   hal_pin_inst_t hv_fan;
   hal_pin_inst_t mot_fan;
   hal_pin_inst_t print;
   hal_pin_inst_t brake_release;
};
