#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct fb_switch_pin_ctx_t{ // found in shared/comps/fb_switch.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t polecount;
   hal_pin_inst_t track_fb;
   hal_pin_inst_t offset_first_enable;
   hal_pin_inst_t pos_fb;
   hal_pin_inst_t vel_fb;
   hal_pin_inst_t com_fb;
   hal_pin_inst_t joint_fb;
   hal_pin_inst_t state;
   hal_pin_inst_t cmd_pos;
   hal_pin_inst_t mot_pos;
   hal_pin_inst_t mot_abs_pos;
   hal_pin_inst_t mot_polecount;
   hal_pin_inst_t mot_offset;
   hal_pin_inst_t mot_state;
   hal_pin_inst_t mot_rev;
   hal_pin_inst_t mot_fb_no_offset;
   hal_pin_inst_t mot_abs_fb_no_offset;
   hal_pin_inst_t plot_fb_pos;
   hal_pin_inst_t com_pos;
   hal_pin_inst_t com_abs_pos;
   hal_pin_inst_t com_polecount;
   hal_pin_inst_t com_offset;
   hal_pin_inst_t com_state;
   hal_pin_inst_t com_rev;
   hal_pin_inst_t com_fb_no_offset;
   hal_pin_inst_t joint_pos;
   hal_pin_inst_t joint_abs_pos;
   hal_pin_inst_t joint_offset;
   hal_pin_inst_t joint_state;
   hal_pin_inst_t joint_rev;
   hal_pin_inst_t joint_fb_no_offset;
   hal_pin_inst_t mot_joint_ratio;
   hal_pin_inst_t phase_time;
   hal_pin_inst_t phase_cur;
   hal_pin_inst_t phase_gain;
   hal_pin_inst_t offset;
   hal_pin_inst_t id;
   hal_pin_inst_t current_com_pos;
   hal_pin_inst_t en;
};
