#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct field_pin_ctx_t{ // found in shared/comps/field.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t vele_n;
   hal_pin_inst_t velm_n;
   hal_pin_inst_t i_n;
   hal_pin_inst_t t_n;
   hal_pin_inst_t vel_boost;
   hal_pin_inst_t t_boost;
   hal_pin_inst_t vel;
   hal_pin_inst_t vel_mode;
   hal_pin_inst_t in_mode;
   hal_pin_inst_t t;
   hal_pin_inst_t iq;
   hal_pin_inst_t id;
   hal_pin_inst_t iq_max;
   hal_pin_inst_t iq_min;
   hal_pin_inst_t t_max;
   hal_pin_inst_t t_min;
   hal_pin_inst_t slip;
   hal_pin_inst_t velm;
   hal_pin_inst_t vele;
};
