#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct fmove_pin_ctx_t{ // found in shared/comps/fmove.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t en;
   hal_pin_inst_t gravity;
   hal_pin_inst_t real_mass;
   hal_pin_inst_t virtual_mass;
   hal_pin_inst_t damping;
   hal_pin_inst_t friction;
   hal_pin_inst_t min_pos;
   hal_pin_inst_t max_pos;
   hal_pin_inst_t max_vel;
   hal_pin_inst_t max_acc;
   hal_pin_inst_t max_usr_vel;
   hal_pin_inst_t max_usr_acc;
   hal_pin_inst_t scale;
   hal_pin_inst_t force_in;
   hal_pin_inst_t force;
   hal_pin_inst_t force_offset;
   hal_pin_inst_t force_offset_lpf;
   hal_pin_inst_t pos;
   hal_pin_inst_t mpos;
   hal_pin_inst_t vel;
   hal_pin_inst_t vel_old;
   hal_pin_inst_t acc;
   hal_pin_inst_t target;
   hal_pin_inst_t force_time;
   hal_pin_inst_t force_timer;
   hal_pin_inst_t force_th;
   hal_pin_inst_t print_freq;
   hal_pin_inst_t print_timer;
   hal_pin_inst_t mode;
};
