#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct hal_test_pin_ctx_t{ // found in shared/comps/hal_test.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t rt_wait;
   hal_pin_inst_t frt_wait;
};
