#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct home_pin_ctx_t{ // found in shared/comps/home.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t home_vel;
   hal_pin_inst_t home_acc;
   hal_pin_inst_t pos_in;
   hal_pin_inst_t pos_out;
   hal_pin_inst_t vel;
   hal_pin_inst_t home_in;
   hal_pin_inst_t home_polarity;
   hal_pin_inst_t offset;
   hal_pin_inst_t home_offset;
   hal_pin_inst_t home_pos;
   hal_pin_inst_t state;
   hal_pin_inst_t en_in;
   hal_pin_inst_t en_out;
   hal_pin_inst_t re_home;
};
