#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct idx_home_pin_ctx_t{ // found in shared/comps/idx_home.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t mot_state;
   hal_pin_inst_t fb;
   hal_pin_inst_t fb_abs;
   hal_pin_inst_t index_en;
   hal_pin_inst_t index_clear;
   hal_pin_inst_t pos_out;
};
