#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct iit_pin_ctx_t{ // found in shared/comps/iit.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t amb_temp;
   hal_pin_inst_t high_temp;
   hal_pin_inst_t max_temp;
   hal_pin_inst_t max_cur;
   hal_pin_inst_t cur_boost;
   hal_pin_inst_t max_time;
   hal_pin_inst_t temp;
   hal_pin_inst_t cur;
};
