#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct jog_pin_ctx_t{ // found in shared/comps/jog.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t jog;
};
