#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct linrev_pin_ctx_t{ // found in shared/comps/linrev.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t scale;
   hal_pin_inst_t cmd_in;
   hal_pin_inst_t cmd_out;
   hal_pin_inst_t cmd_d_in;
   hal_pin_inst_t cmd_d_out;
   hal_pin_inst_t fb_in;
   hal_pin_inst_t fb_out;
   hal_pin_inst_t fb_d_in;
   hal_pin_inst_t fb_d_out;
   hal_pin_inst_t rev_clear;
   hal_pin_inst_t rev;
};
