#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct mad_pin_ctx_t{ // found in shared/comps/mad.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t in;
   hal_pin_inst_t mult;
   hal_pin_inst_t add;
   hal_pin_inst_t out;
};
