#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct mpid_pin_ctx_t{ // found in shared/comps/mpid.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t pos_ext_cmd;
   hal_pin_inst_t pos_fb;
   hal_pin_inst_t old_pos_ext_cmd;
   hal_pin_inst_t old_pos_fb;
   hal_pin_inst_t pos_error;
   hal_pin_inst_t vel_ext_cmd;
   hal_pin_inst_t vel_fb;
   hal_pin_inst_t vel_error;
   hal_pin_inst_t vel_cmd;
   hal_pin_inst_t acc_cmd;
   hal_pin_inst_t torque_ext_cmd;
   hal_pin_inst_t torque_sum;
   hal_pin_inst_t torque_cmd;
   hal_pin_inst_t min_pos_error;
   hal_pin_inst_t max_vel;
   hal_pin_inst_t max_acc;
   hal_pin_inst_t max_torque;
   hal_pin_inst_t pos_p;
   hal_pin_inst_t vel_i;
   hal_pin_inst_t vel_p;
   hal_pin_inst_t j;
   hal_pin_inst_t scale;
   hal_pin_inst_t en;
};
