#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct mux_pin_ctx_t{ // found in shared/comps/mux.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t in[80];
   hal_pin_inst_t out[10];
   hal_pin_inst_t mux;
};
