#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct or_pin_ctx_t{ // found in shared/comps/or.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t in0;
   hal_pin_inst_t in1;
   hal_pin_inst_t in2;
   hal_pin_inst_t in3;
   hal_pin_inst_t out;
};
