#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct pe_pin_ctx_t{ // found in shared/comps/pe.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t udc;
   hal_pin_inst_t idc;
   hal_pin_inst_t ud;
   hal_pin_inst_t uq;
   hal_pin_inst_t id;
   hal_pin_inst_t iq;
   hal_pin_inst_t torque;
   hal_pin_inst_t vel;
   hal_pin_inst_t r;
   hal_pin_inst_t j;
   hal_pin_inst_t cap;
   hal_pin_inst_t e_el;
   hal_pin_inst_t e_kin;
   hal_pin_inst_t p_el_dc;
   hal_pin_inst_t p_el_ac;
   hal_pin_inst_t p_m;
   hal_pin_inst_t p_t;
};
