#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct pmsm_ttc_pin_ctx_t{ // found in shared/comps/pmsm_ttc.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t psi;
   hal_pin_inst_t polecount;
   hal_pin_inst_t ac;
   hal_pin_inst_t pc;
   hal_pin_inst_t nc;
   hal_pin_inst_t ae;
   hal_pin_inst_t pe;
   hal_pin_inst_t ne;
   hal_pin_inst_t pos_in;
   hal_pin_inst_t pos_out;
   hal_pin_inst_t t;
   hal_pin_inst_t g;
   hal_pin_inst_t block_gain;
   hal_pin_inst_t torque;
   hal_pin_inst_t cur;
};
