#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct pmsm_limits_pin_ctx_t{ // found in shared/comps/pmsm_limits.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t psi;
   hal_pin_inst_t r;
   hal_pin_inst_t ld;
   hal_pin_inst_t lq;
   hal_pin_inst_t polecount;
   hal_pin_inst_t ac_volt;
   hal_pin_inst_t next_max_cur;
   hal_pin_inst_t next_max_torque;
   hal_pin_inst_t next_min_cur;
   hal_pin_inst_t next_min_torque;
   hal_pin_inst_t max_cur;
   hal_pin_inst_t max_torque;
   hal_pin_inst_t min_cur;
   hal_pin_inst_t min_torque;
   hal_pin_inst_t abs_max_cur;
   hal_pin_inst_t abs_max_torque;
   hal_pin_inst_t abs_max_vel;
   hal_pin_inst_t iq;
   hal_pin_inst_t indq;
};
