#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct psi_pin_ctx_t{ // found in shared/comps/psi.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t vel;
   hal_pin_inst_t dc_volt;
   hal_pin_inst_t u;
   hal_pin_inst_t v;
   hal_pin_inst_t w;
   hal_pin_inst_t polecount;
   hal_pin_inst_t psi;
   hal_pin_inst_t max_psi;
};
