#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct ramp_pin_ctx_t{ // found in shared/comps/ramp.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t vel_ext_cmd;
   hal_pin_inst_t en;
   hal_pin_inst_t scale;
   hal_pin_inst_t max_vel;
   hal_pin_inst_t max_acc;
   hal_pin_inst_t at_speed_th;
   hal_pin_inst_t vel_cmd;
   hal_pin_inst_t at_speed;
   hal_pin_inst_t en_out;
   hal_pin_inst_t en_timer;
   hal_pin_inst_t en_delay;
};
