#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct reslimit_pin_ctx_t{ // found in shared/comps/reslimit.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t pos_in;
   hal_pin_inst_t pos_out;
   hal_pin_inst_t res;
};
