#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct rev_pin_ctx_t{ // found in shared/comps/rev.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t in;
   hal_pin_inst_t out;
   hal_pin_inst_t in_d;
   hal_pin_inst_t out_d;
   hal_pin_inst_t rev;
};
