#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct rl_pin_ctx_t{ // found in shared/comps/rl.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t r_test_cur;
   hal_pin_inst_t l_test_volt;
   hal_pin_inst_t r_test_time;
   hal_pin_inst_t l_test_time;
   hal_pin_inst_t ud_cmd;
   hal_pin_inst_t ud_fb;
   hal_pin_inst_t id_fb;
   hal_pin_inst_t uq_cmd;
   hal_pin_inst_t uq_fb;
   hal_pin_inst_t iq_fb;
   hal_pin_inst_t ki;
   hal_pin_inst_t en;
   hal_pin_inst_t en_out;
   hal_pin_inst_t state;
   hal_pin_inst_t timer;
   hal_pin_inst_t counter;
   hal_pin_inst_t r;
   hal_pin_inst_t ur;
   hal_pin_inst_t ir;
   hal_pin_inst_t ld;
   hal_pin_inst_t lq;
   hal_pin_inst_t u0;
   hal_pin_inst_t u1;
   hal_pin_inst_t i0;
   hal_pin_inst_t i1;
   hal_pin_inst_t et;
};
