#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct rlpsij_pin_ctx_t{ // found in shared/comps/rlpsij.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t r;
   hal_pin_inst_t l;
   hal_pin_inst_t psi;
   hal_pin_inst_t j;
   hal_pin_inst_t load;
   hal_pin_inst_t friction;
   hal_pin_inst_t damping;
   hal_pin_inst_t polecount;
   hal_pin_inst_t fb_offset;
   hal_pin_inst_t cmd_mode;
   hal_pin_inst_t q_cmd;
   hal_pin_inst_t d_cmd;
   hal_pin_inst_t iq_fb;
   hal_pin_inst_t id_fb;
   hal_pin_inst_t uq_fb;
   hal_pin_inst_t ud_fb;
   hal_pin_inst_t abs_pos_fb;
   hal_pin_inst_t com_pos;
   hal_pin_inst_t en_out;
   hal_pin_inst_t en;
   hal_pin_inst_t test_cur;
   hal_pin_inst_t test_vel;
   hal_pin_inst_t rl_ki;
   hal_pin_inst_t vel_ki;
   hal_pin_inst_t vel_kp;
   hal_pin_inst_t rl_time;
   hal_pin_inst_t vel_time;
   hal_pin_inst_t lpf;
   hal_pin_inst_t timer;
   hal_pin_inst_t multi_pos;
   hal_pin_inst_t state;
   hal_pin_inst_t vel;
   hal_pin_inst_t acc;
   hal_pin_inst_t last_pos;
   hal_pin_inst_t error_sum;
   hal_pin_inst_t i[4];
};
