#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct scale_pin_ctx_t{ // found in shared/comps/scale.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t in0;
   hal_pin_inst_t out0;
   hal_pin_inst_t in1;
   hal_pin_inst_t out1;
   hal_pin_inst_t scale;
};
