#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct spid_pin_ctx_t{ // found in shared/comps/spid.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t cmd;
   hal_pin_inst_t fb;
   hal_pin_inst_t en;
   hal_pin_inst_t kp;
   hal_pin_inst_t ki;
   hal_pin_inst_t kd;
   hal_pin_inst_t ksd;
   hal_pin_inst_t kdi;
   hal_pin_inst_t ksdi;
   hal_pin_inst_t kff0;
   hal_pin_inst_t kff1;
   hal_pin_inst_t offset;
   hal_pin_inst_t min_output;
   hal_pin_inst_t max_output;
   hal_pin_inst_t max_error;
   hal_pin_inst_t output;
   hal_pin_inst_t error;
   hal_pin_inst_t sat;
};
