#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct stp_pin_ctx_t{ // found in shared/comps/stp.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t target;
   hal_pin_inst_t vel_ext_cmd;
   hal_pin_inst_t acc_ext_cmd;
   hal_pin_inst_t jog;
   hal_pin_inst_t pos;
   hal_pin_inst_t mpos;
   hal_pin_inst_t vel_cmd;
   hal_pin_inst_t acc_cmd;
   hal_pin_inst_t max_pos;
   hal_pin_inst_t min_pos;
   hal_pin_inst_t max_vel;
   hal_pin_inst_t max_acc;
   hal_pin_inst_t dtg;
   hal_pin_inst_t ttg;
   hal_pin_inst_t at_target;
};
