#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct svm_pin_ctx_t{ // found in shared/comps/svm.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t u;
   hal_pin_inst_t v;
   hal_pin_inst_t w;
   hal_pin_inst_t udc;
   hal_pin_inst_t su;
   hal_pin_inst_t sv;
   hal_pin_inst_t sw;
   hal_pin_inst_t cmode;
   hal_pin_inst_t mode;
   hal_pin_inst_t enu;
   hal_pin_inst_t env;
   hal_pin_inst_t enw;
};
