#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct term_pin_ctx_t{ // found in shared/comps/term.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t wave[8];
   hal_pin_inst_t offset[8];
   hal_pin_inst_t gain[8];
   hal_pin_inst_t send_step;
   hal_pin_inst_t con;
};
