#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct th_pin_ctx_t{ // found in shared/comps/th.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t in;
   hal_pin_inst_t in_lpf;
   hal_pin_inst_t in_lp;
   hal_pin_inst_t min;
   hal_pin_inst_t max;
   hal_pin_inst_t out;
   hal_pin_inst_t out_not;
};
