#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct uf_pin_ctx_t{ // found in shared/comps/uf2.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t u_n;
   hal_pin_inst_t vel_n;
   hal_pin_inst_t polecount;
   hal_pin_inst_t cur_n;
   hal_pin_inst_t slip_n;
   hal_pin_inst_t scale;
   hal_pin_inst_t vel_cmd;
   hal_pin_inst_t cur;
   hal_pin_inst_t u_cmd;
   hal_pin_inst_t vel_cmd_out;
   hal_pin_inst_t com_pos;
   hal_pin_inst_t load;
};
