#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct uvw_pin_ctx_t{ // found in shared/comps/uvw.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t u;
   hal_pin_inst_t v;
   hal_pin_inst_t w;
   hal_pin_inst_t amp;
   hal_pin_inst_t timer;
   hal_pin_inst_t en_time;
   hal_pin_inst_t mode;
   hal_pin_inst_t led;
   hal_pin_inst_t p0;
   hal_pin_inst_t p1;
   hal_pin_inst_t p2;
   hal_pin_inst_t p3;
   hal_pin_inst_t p4;
   hal_pin_inst_t p5;
   hal_pin_inst_t p6;
   hal_pin_inst_t p7;
   hal_pin_inst_t pos;
   hal_pin_inst_t rpos;
   hal_pin_inst_t state;
   hal_pin_inst_t error;
};
