#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct vel_int_pin_ctx_t{ // found in shared/comps/vel_int.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t pos_in;
   hal_pin_inst_t pos_out;
   hal_pin_inst_t vel_in;
   hal_pin_inst_t vel_out;
   hal_pin_inst_t cmd_freq;
   hal_pin_inst_t real_cmd_freq;
   hal_pin_inst_t wd;
   hal_pin_inst_t error;
};
