#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct vel_pin_ctx_t{ // found in shared/comps/vel.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t pos_in;
   hal_pin_inst_t pos_out;
   hal_pin_inst_t vel;
   hal_pin_inst_t acc;
   hal_pin_inst_t w;
   hal_pin_inst_t d;
   hal_pin_inst_t g;
   hal_pin_inst_t h;
   hal_pin_inst_t j;
   hal_pin_inst_t lp;
   hal_pin_inst_t torque;
   hal_pin_inst_t vel_ff;
   hal_pin_inst_t en;
   hal_pin_inst_t pos_error;
};
