#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct velbuf_pin_ctx_t{ // found in shared/comps/velbuf.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t pos;
   hal_pin_inst_t vel;
   hal_pin_inst_t vel_lp;
   hal_pin_inst_t min_pos_diff;
   hal_pin_inst_t lpf;
   hal_pin_inst_t diff_time;
   hal_pin_inst_t diff_pos;
};
