#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct veltopos_pin_ctx_t{ // found in shared/comps/veltopos.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t vel;
   hal_pin_inst_t vel_fb;
   hal_pin_inst_t max_acc;
   hal_pin_inst_t max_vel;
   hal_pin_inst_t polecount;
   hal_pin_inst_t pos;
};
