#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct veltime_pin_ctx_t{ // found in shared/comps/veltime.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t pos;
   hal_pin_inst_t old_pos;
   hal_pin_inst_t timer;
   hal_pin_inst_t vel;
   hal_pin_inst_t vel_lp;
   hal_pin_inst_t max_time;
   hal_pin_inst_t lpf;
};
