#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct ypid_pin_ctx_t{ // found in shared/comps/ypid.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t pos_ext_cmd;
   hal_pin_inst_t pos_fb;
   hal_pin_inst_t pos_error;
   hal_pin_inst_t vel_ext_cmd;
   hal_pin_inst_t vel_fb;
   hal_pin_inst_t vel_cmd;
   hal_pin_inst_t vel_error;
   hal_pin_inst_t vel_min;
   hal_pin_inst_t enable;
   hal_pin_inst_t out;
   hal_pin_inst_t pos_p;
   hal_pin_inst_t vel_p;
   hal_pin_inst_t vel_i;
   hal_pin_inst_t vel_ff;
   hal_pin_inst_t max_vel;
   hal_pin_inst_t max_acc;
   hal_pin_inst_t max_out;
   hal_pin_inst_t vel_sat;
   hal_pin_inst_t out_sat;
   hal_pin_inst_t saturated;
};
