#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct adc_pin_ctx_t{ // found in src/comps/adc.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t sin0;
   hal_pin_inst_t cos0;
   hal_pin_inst_t sin0l;
   hal_pin_inst_t cos0l;
   hal_pin_inst_t quad;
   hal_pin_inst_t amp0;
   hal_pin_inst_t sin1;
   hal_pin_inst_t cos1;
   hal_pin_inst_t sin1l;
   hal_pin_inst_t cos1l;
   hal_pin_inst_t amp1;
   hal_pin_inst_t res_mode;
   hal_pin_inst_t sin_gain;
   hal_pin_inst_t cos_gain;
   hal_pin_inst_t sin_offset;
   hal_pin_inst_t cos_offset;
   hal_pin_inst_t send_step;
   hal_pin_inst_t offset[8];
   hal_pin_inst_t gain[8];
};
