#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct enc_cmd_pin_ctx_t{ // found in src/comps/enc_cmd.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t res;
   hal_pin_inst_t pos;
   hal_pin_inst_t a;
   hal_pin_inst_t b;
   hal_pin_inst_t fault;
   hal_pin_inst_t mode;
   hal_pin_inst_t remap;
   hal_pin_inst_t input_filter;
};
