#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct enc_fb_pin_ctx_t{ // found in src/comps/enc_fb.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t res;
   hal_pin_inst_t ires;
   hal_pin_inst_t pos;
   hal_pin_inst_t abs_pos;
   hal_pin_inst_t state;
   hal_pin_inst_t index;
   hal_pin_inst_t a;
   hal_pin_inst_t b;
   hal_pin_inst_t ipos;
   hal_pin_inst_t sin;
   hal_pin_inst_t cos;
   hal_pin_inst_t quad;
   hal_pin_inst_t oquad;
   hal_pin_inst_t oquadoff;
   hal_pin_inst_t qdiff;
   hal_pin_inst_t error;
   hal_pin_inst_t amp;
   hal_pin_inst_t vel;
   hal_pin_inst_t ccr3;
   hal_pin_inst_t en_index;
   hal_pin_inst_t indexprint;
};
