#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct encf_pin_ctx_t{ // found in src/comps/encf.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t error;
   hal_pin_inst_t dma;
   hal_pin_inst_t pos;
   hal_pin_inst_t abs_pos;
   hal_pin_inst_t state;
   hal_pin_inst_t turns;
   hal_pin_inst_t com_pos;
   hal_pin_inst_t index;
   hal_pin_inst_t req_len;
   hal_pin_inst_t send_step;
   hal_pin_inst_t crc_ok;
   hal_pin_inst_t crc_er;
   hal_pin_inst_t freq;
   hal_pin_inst_t bit_ticks;
};
