#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct encs_pin_ctx_t{ // found in src/comps/encs.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t pos;
   hal_pin_inst_t error;
   hal_pin_inst_t state;
};
