#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct endat_pin_ctx_t{ // found in src/comps/endat.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t pos;
   hal_pin_inst_t mpos;
   hal_pin_inst_t f1;
   hal_pin_inst_t crc;
   hal_pin_inst_t shift;
   hal_pin_inst_t timer;
   hal_pin_inst_t swap;
   hal_pin_inst_t skip;
   hal_pin_inst_t bytes;
   hal_pin_inst_t error;
   hal_pin_inst_t state;
   hal_pin_inst_t endat_error;
   hal_pin_inst_t endat_warning;
   hal_pin_inst_t endat_state;
   hal_pin_inst_t pos_len;
   hal_pin_inst_t mpos_len;
   hal_pin_inst_t pos_res;
   hal_pin_inst_t type;
   hal_pin_inst_t max_vel;
   hal_pin_inst_t req;
   hal_pin_inst_t print_time;
};
