#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct hx_pin_ctx_t{ // found in src/comps/hx711.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t out0;
   hal_pin_inst_t out1;
   hal_pin_inst_t gain;
   hal_pin_inst_t offset;
   hal_pin_inst_t sleep;
   hal_pin_inst_t clk_inv;
   hal_pin_inst_t data_inv;
   hal_pin_inst_t timer;
   hal_pin_inst_t time;
};
