#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct o_fb_pin_ctx_t{ // found in src/comps/o_fb.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t a;
   hal_pin_inst_t b;
};
