#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct res_pin_ctx_t{ // found in src/comps/res.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t pos;
   hal_pin_inst_t amp;
   hal_pin_inst_t quad;
   hal_pin_inst_t poles;
   hal_pin_inst_t min_amp;
   hal_pin_inst_t vel;
   hal_pin_inst_t sin;
   hal_pin_inst_t cos;
   hal_pin_inst_t enable;
   hal_pin_inst_t error;
   hal_pin_inst_t state;
   hal_pin_inst_t phase;
   hal_pin_inst_t res_mode;
   hal_pin_inst_t freq;
};
