#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct smartabs_pin_ctx_t{ // found in src/comps/smartabs.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t pos;
   hal_pin_inst_t error;
   hal_pin_inst_t state;
   hal_pin_inst_t dma;
   hal_pin_inst_t a0;
   hal_pin_inst_t a1;
   hal_pin_inst_t a2;
   hal_pin_inst_t a3;
   hal_pin_inst_t a4;
   hal_pin_inst_t a5;
};
