#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct sserial_pin_ctx_t{ // found in src/comps/sserial.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t error;
   hal_pin_inst_t crc_error;
   hal_pin_inst_t connected;
   hal_pin_inst_t timeout;
   hal_pin_inst_t pos_cmd;
   hal_pin_inst_t pos_cmd_d;
   hal_pin_inst_t pos_fb;
   hal_pin_inst_t vel_fb;
   hal_pin_inst_t current;
   hal_pin_inst_t scale;
   hal_pin_inst_t clock_scale;
   hal_pin_inst_t available;
   hal_pin_inst_t phase;
   hal_pin_inst_t in0;
   hal_pin_inst_t in1;
   hal_pin_inst_t in2;
   hal_pin_inst_t in3;
   hal_pin_inst_t fault;
   hal_pin_inst_t out0;
   hal_pin_inst_t out1;
   hal_pin_inst_t out2;
   hal_pin_inst_t out3;
   hal_pin_inst_t enable;
   hal_pin_inst_t index_clear;
   hal_pin_inst_t index_out;
   hal_pin_inst_t pos_advance;
};
