#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct usart_pin_ctx_t{ // found in src/comps/usart.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t req;
   hal_pin_inst_t print;
   hal_pin_inst_t freq;
   hal_pin_inst_t dma;
   hal_pin_inst_t pos_offset;
   hal_pin_inst_t pos_len;
   hal_pin_inst_t pos;
};
