#pragma once
//generated by tools/create_comp_h.py DO NOT EDIT

#include "hal.h"
struct yaskawa_pin_ctx_t{ // found in src/comps/yaskawa.c
   hal_pin_inst_t rt_prio;
   hal_pin_inst_t frt_prio;
   hal_pin_inst_t pos;
   hal_pin_inst_t error;
   hal_pin_inst_t error_sum;
   hal_pin_inst_t dump;
   hal_pin_inst_t len;
   hal_pin_inst_t off;
   hal_pin_inst_t len2;
   hal_pin_inst_t off2;
   hal_pin_inst_t probe2;
   hal_pin_inst_t len3;
   hal_pin_inst_t len4;
   hal_pin_inst_t len5;
   hal_pin_inst_t probe3;
   hal_pin_inst_t probe4;
   hal_pin_inst_t probe5;
   hal_pin_inst_t send;
   hal_pin_inst_t crc_ok;
   hal_pin_inst_t crc_error;
};
