#!/usr/bin/env python

import re
import sys

comps = []

header = open(sys.argv[1] + '/tab.h', 'w')
code = open(sys.argv[1] + '/tab.c', 'w')

for infile in sys.argv[2:]:
    with open(infile) as f:
        pins = []
        compname = ''
        for line in f:
            comp = re.search('HAL_COMP\((\w*)\);', line)
            if comp:
                compname = comp.groups()[0]
            pin = re.search('HAL_PIN\((\w*)\)', line)
            if pin:
                pins.append(pin.groups()[0])
        comps.append((compname,pins))

header.write("#pragma once\n")
header.write("//generated by " + sys.argv[0] + " DO NOT EDIT\n")

for c in comps:
    header.write("struct " + c[0] + "_pin_ctx_t{\n")
    for p in c[1]:
        header.write("   hal_pin_inst_t " + p + ";\n")
    header.write("}\n\n")

for c in comps:
    header.write("extern " + c[0] + "_comp_struct;\n")

header.write("extern const uint32_t comp_count;\n")
header.write("extern const uint32_t pin_count;)\n")

code.write("#include \"hal2.h\"\n")
code.write("//generated by " + sys.argv[0] + " DO NOT EDIT\n")
code.write("hal_comp_t comps[] = {\n")
for c in comps:
   code.write("   " + c[0] + "_comp_struct,\n")
code.write("}\n\n")
code.write("const uint32_t comp_count = sizeof(comps) / sizeof(comps[0]);\n\n")

code.write("pin_t pins[] = {\n")
for c in comps:
    for p in c[1]:
        code.write("   \"" + p + "\",\n")
code.write("}\n\n")
code.write("const uint32_t pin_count = sizeof(pins) / sizeof(pins[0]);\n\n")

header.close()
code.close()